src/components/MessageQuickstart.tsx
External link to correct explorer anchors
=> Patch quickstart explorer links

docusaurus.config.js, src/components/HomepageFeatures/index.js
=> Update docusaurus.config.js descriptions

docs/deploy-hyperlane.mdx, docs/guides/deploy-warp-route-UI.mdx, docs/guides/deploy-warp-route.mdx, docs/reference/applications/warp-routes.mdx, sidebars.js
Fixes https://github.com/hyperlane-xyz/issues/issues/715
Requires https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3006 to be shipped first
=> Update warp deploy instructions

src/components/MessageQuickstart.tsx
- Add Hyperlane CLI to quickstart
- Make hyperlane CLI default quickstart
- Fixes https://github.com/hyperlane-xyz/issues/issues/745
=> cli send quickstart

docs/guides/developer-tips/unit-testing.mdx
fixes: https://github.com/hyperlane-xyz/issues/issues/725
=> feat:add local unit testing page

docs/deploy-hyperlane-troubleshooting.mdx, sidebars.js
- https://github.com/hyperlane-xyz/issues/issues/909
- https://github.com/hyperlane-xyz/issues/issues/839
- https://github.com/hyperlane-xyz/issues/issues/908
=> feat: add deploy-hyperlane-troubleshooting page

src/components/InteractiveExample.tsx
https://github.com/hyperlane-xyz/issues/issues/907
=> fix: `destinationDomain` now correctly set using `destinationChain`

docs/guides/deploy-warp-route.mdx
this should fix deploys from main now
=> fix: warp route link

docs/guides/deploy-warp-route-UI.mdx, docs/partials/ts-sdk-placeholder.mdx, docs/protocol/ISM/economic-security.mdx, docs/reference/typescript-sdk/app-abstraction.mdx, docs/reference/typescript-sdk/deploying-contracts.mdx, docs/reference/typescript-sdk/multiprovider.mdx, docs/reference/typescript-sdk/quoting-gas.mdx, docs/reference/typescript-sdk/sdk-overview.mdx, docs/reference/typescript-sdk/testing-contracts.mdx, docusaurus.config.js
resolves https://github.com/hyperlane-xyz/issues/issues/992
=> feat: setup v2 sitemap redirects to v3

docs/operate/validators/run-validators.mdx
A reorg period of 20 is too high
=> Lower reorgPeriod in docs

docs/guides/deploy-warp-route-UI.mdx, docs/guides/developer-tips/explorer-debugging/configuring-pi-chains.mdx, docs/guides/developer-tips/explorer-debugging/rest-api.mdx, docs/guides/latencies.mdx, docs/guides/token-faucets.mdx, docs/reference/domains.mdx, docs/reference/hooks/op-stack.mdx, static/addresses/testnet.json, static/addresses/testrecipients.json, static/chainmetadata/testnet.json
following on from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3389
resolves https://github.com/hyperlane-xyz/issues/issues/991
=> feat: remove goerli references

docs/guides/implementation-guide.mdx
resolves https://github.com/hyperlane-xyz/issues/issues/950
TODO:
=> feat: update implementation guide

sidebars.js
fixes https://github.com/hyperlane-xyz/issues/issues/1131
=> fix: link custom ism page from sidebar

docs/guides/deploy-warp-route.mdx
as per https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3416
I think it makes sense to just update the Base section with details on the new type. The CLI will be used to create a new YB route with new prompts (see https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3435)
=> Update Base config section

docs/guides/deploy-warp-route.mdx, docs/partials/deploy-hyperlane/_deploy-warp-route.mdx
to be merged after https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3470
=> feat: rename warp-ui-token-config to warp-config

docs/guides/v2-to-v3-migration.mdx, docs/protocol/interchain-gas-payment.mdx, docs/reference/hooks/interchain-gas.mdx, docs/reference/messaging/send.mdx
resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3203 
resolves https://github.com/hyperlane-xyz/v3-docs/issues/51
=> feat: update igp docs

docs/partials/deploy-hyperlane/_deploy-contracts.mdx
* Adds new dry-run feature info to new deploy section
=> Add Dry Run Info

package.json, sidebars.js, yarn.lock
- update to latest registry
- make docs deploy work again
=> feat: update to latest registry

docs/guides/deploy-hyperlane-local-agents.mdx, docs/operate/relayer/run-relayer.mdx, docs/operate/run-docker-compose.mdx, docs/operate/validators/run-validators.mdx, docs/reference/applications/interchain-account.mdx
- Updated docker image tag from `3adc0e9-20240319-152359` to `36e9a2e-20240607-155048`
=> fix: update agent image tags

docs/guides/deploy-warp-route-UI.mdx, sidebars.js
- Update warp UI docs for registry
- Tweak guides sidebar order
=> Update warp UI guide

docs/guides/deploy-hyperlane-local-agents.mdx, docs/operate/relayer/run-relayer.mdx, docs/operate/run-docker-compose.mdx, docs/operate/validators/run-validators.mdx
to include chains added in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3960
=> chore: update docker images to include latest chain deployments

docs/deploy-hyperlane.mdx, docs/guides/deploy-hyperlane-local-agents.mdx, docs/guides/deploy-warp-route.mdx, docs/partials/deploy-hyperlane/_cli-chains.mdx
- Update https://docs.hyperlane.xyz/docs/deploy-hyperlane#5-optional-deploy-a-warp-route
- Update relevant commands to cli-4
- Add warning to https://docs.hyperlane.xyz/docs/guides/deploy-hyperlane-local-agents to note stale guide
=> Update deploy hyperlane to quickstart 

docs/deploy-hyperlane.mdx
Some small nits and adjustments after going through the new CLI experience
=> chore: small tweaks for CLI 2.0's "Deploy Hyperlane to a new chain"

docs/deploy-hyperlane.mdx, docs/guides/deploy-warp-route.mdx, docs/operate/relayer/run-relayer.mdx, sidebars.js
- Update "Deploy Hyperlane to a new chain" according to Rossy's [unaddressed comments](https://github.com/hyperlane-xyz/v3-docs/pull/127/files)
- Move Warp Route section to "Deploy a Warp Route"
- Update "Deploy a Warp Route" to reflect the link, and content
=> Update Deploy Hyperlane and Warp Route

package.json, yarn.lock
chore: update registry to 2.2.0
=> chore: update registry to 2.2.0

docs/guides/deploy-warp-route-UI.mdx
Replace weth logo by usdc logo.
=> fix: Replace weth logo by usdc logo in warp-route-UI

docs/protocol/interchain-gas-payment.mdx, docs/reference/hooks/interchain-gas.mdx
- spell out the fees charged to message senders
=> feat(protocol): Explain fee calculation in interchain gas payments

docs/deploy-hyperlane.mdx, docs/guides/deploy-hyperlane-local-agents.mdx, docs/partials/deploy-hyperlane/_deploy-contracts.mdx, docs/partials/deploy-hyperlane/_send-test-messages.mdx
- Updates with latest CLI commands
- Link from "Deploy Hyperlane to a new chain"
- Add initialize agent config section
=> Update "Deploy Hyperlane with Local Agents" page 

docs/guides/avs-operator-guide.mdx, docs/operate/docker-quickstart.mdx, docs/operate/run-docker-compose.mdx, docs/operate/validators/docker-quickstart.mdx, sidebars.js
Add step by step guide for streamlined operator onboarding, mentioned in #142 
thanks!
=> docker-compose step-by-step guide

docs/operate/docker-quickstart.mdx, docs/operate/validators/run-validators.mdx, docusaurus.config.js, sidebars.js
feat: unify docker compose guides
follow up to https://github.com/hyperlane-xyz/v3-docs/pull/144
fixes: https://github.com/hyperlane-xyz/v3-docs/issues/142
=> feat: unify docker compose guides

docusaurus.config.js
=> fix: add avs redirect 

docs/guides/deploy-warp-route.mdx
=> chore: remove repetitive words

package.json, yarn.lock
chore: update registry to v2.4.0
=> chore: update registry to v2.4.0

package.json, yarn.lock
chore: update to registry v2.5.0
=> chore: update to registry v2.5.0

docs/core-production.mdx
- Add instructions for productionizing a core deployment
=> feat(guides): Add productionizing core instructions

package.json, yarn.lock
chore: update to registry v4.5.0
=> chore: update to registry v4.5.0

docs/operate/set-up-agent-keys.mdx, docs/operate/validators/validator-signatures-aws.mdx
When reading the guide I had completely skipped reading step 1 because I thought it's only required for KMS. It's more visible in step 2 imo
=> chore: s3 setup nit

docs/intro.mdx, sidebars.js
- Renamed "Choose Hyperlane" to "Intro to Hyperlane."
- Updated the description for clarity 
- Added subsections: "What is Hyperlane," "Why Hyperlane" & "Start Building with Hyperlane"
- Kept pre-built examples and added links
=> Update and rename choose hyperlane section 

docs/guides/avs-operator-guide.mdx
=> chore: correct typo

src/components/ReorgPeriodTable.tsx
chore: filter reorg period table
=> chore: filter reorg period table

docs/partials/reference/_default-isms.mdx
feat: update validators for new batch
=> feat: update validators for new batch

docs/guides/deploy-hyperlane-local-agents.mdx, docs/guides/quickstart-relayer.mdx, docs/guides/quickstart-validator.mdx, docs/operate/docker-quickstart.mdx, docs/operate/run-docker-compose.mdx
chore: update agents to v1.0.0
=> chore: update agents to v1.0.0

docs/operate/relayer/run-relayer.mdx, docs/operate/validators/run-validators.mdx
=> chore: update agent image

docs/guides/implementation-guide.mdx
fix: update agent links in implementation guide
fixing based on report here: https://discord.com/channels/935678348330434570/1303412967345225778/1304251826090147983
=> fix: update agent links in implementation guide

docs/deploy-hyperlane.mdx, docs/guides/deploy-warp-route-UI.mdx, docs/guides/deploy-warp-route.mdx, docs/protocol/warp-routes/warp-routes-custom-gas-fast-native.mdx
do not merge until release of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4831
=> Add ts relayer to docs

docs/partials/reference/_default-isms.mdx
generated by a script forked from this branch which has a bunch of the validator<>alias mappings in-code https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4774
=> chore: update default ISMs

README.md
=> feat: add contributing section to readme 

docs/deploy-hyperlane-troubleshooting.mdx, docs/deploy-hyperlane.mdx
Fix for the chains that do not support getStorageAt()
=> feat: add troubleshooting section for getStorageAt

README.md, docs/guides/deploy-warp-route.mdx, docs/guides/local-testnet-setup.mdx, docs/intro.mdx, docs/protocol/interchain-gas-payment.mdx, docs/reference/hooks/interchain-gas.mdx
- Adding common errors + solution to the local guide
- Add next steps to intro 
- Consolidate IGP and post-dispatch igp sections 
- Oct docs bash: Clarify collateral type selection for warp routes in documentation
=> feat: add local troubleshooting, consolidate IGP, add next steps to intro 

docusaurus.config.js
update the footer for the docs:
Copyright © 2024 Abacus Works, Inc., a core developer team working on Hyperlane
Built IRL in New York 🗽 and London 💂🏼‍♂️
=> fix: update footer

docs/reference/addresses/mailbox-addresses.mdx, docs/reference/domains.mdx, src/components/AddressTable.tsx
- add chainid to mailbox table
- add more warnings about domainid != chainid for some chains
=> chore: domainid/chainid warnings

src/components/DefaultValidators.tsx, src/utils/registry.ts
fix: manually filter pre-mainnet chains
=> fix: manually filter pre-mainnet chains

docs/operate/validators/run-validators.mdx
=> chore: fix 404 status URL

docs/guides/deploy-hyperlane-local-agents.mdx, docs/guides/quickstart-relayer.mdx, docs/guides/quickstart-validator.mdx, docs/operate/docker-quickstart.mdx, docs/operate/relayer/run-relayer.mdx, docs/operate/run-docker-compose.mdx, docs/operate/validators/run-validators.mdx
chore: update default agent image
=> chore: update default agent image

docs/protocol/interchain-gas-payment.mdx, docs/reference/hooks/interchain-gas.mdx
This PR improves the IGP docs with the following updates:
- Added Troubleshooting Section: Covers common issues like GasPaymentRequirementNotMet, high testnet gas prices, fallback routing, and large gas quotes.
- Expanded Metadata Explanations: Clarify msgValue and gasLimit in gas calculations.
- Added section: Determine and Override the Gas Limit
- Added section: Using the Hyperlane explorer for debugging
- Fix misleading metadata encoding example and clarify usage of StandardHookMetadata.formatMetadata
=> feat: Improve Interchain Gas Payment documentation with troubleshooting and update sections

README.md, docs/faq.mdx, docs/operate/validators/monitoring-alerting.mdx
Fix minor issues in documentation
- Removed redundant "yarn" command in installation section.
- Corrected "static contents hosting service" to "content hosting service".
- Reworded contribution guideline to "Submit a pull request (PR) with your changes".
=> Fix minor issues in documentation

docs/operate/config-reference.mdx
- address the open points: https://github.com/hyperlane-xyz/v3-docs/pull/305
- formatting
=> chore: config reference fix & formatting

docs/guides/update-mailbox-default-ism.mdx
the  `defaultIsm` - the `defaultIsm` ( deleted space )
=> remove extra spaces update-mailbox-default-ism.mdx

docs/guides/deploy-warp-route-UI.mdx
YOUR_YOUR_ROUTER_ADDRESS_2 - YOUR_ROUTER_ADDRESS_2
fix duplicate `YOUR`
=> fix deploy-warp-route-UI.mdx

docs/guides/local-testnet-setup.mdx
=> fix duplicate `:` local-testnet-setup.mdx

package.json, yarn.lock
chore: update hyperlane package versions
=> chore: update registry version

package.json, yarn.lock
chore: update hyperlane sdk version
=> chore: update hyperlane sdk version

docs/reference/cosmos-sdk.mdx, sidebars.js
Add new page to the docs on the upcoming release of the cosmos sdk module.
=> feat: add cosmos sdk module section

docs/protocol/protocol-overview.mdx
=> bug: Fix Markdown Rendering Issue in Mermaid Diagram (#341)

docs/protocol/agents/relayer.mdx, docs/protocol/warp-routes/deploy-multicollateral-warp-routes.mdx, sidebars.js
New warp route deployment guide for multicollateral warp routes
=> feat: add new multi-collateral warp route guide

docs/guides/deploy-svm-warp-route.mdx
This PR adds a disclaimer to the SVM warp route deployment, recommending a reasonable amounr for the ATA payer funding.
=> chore: add ATA funding disclaimer

docusaurus.config.js
=> feat: add update footer 

docusaurus.config.js, sidebars.js
- add redirect for "/docs/explorer/"
- add Tools on sidebar for explorer
=> chore: add explorer redirect and update sidebar

docs/guides/deploy-hyperlane-local-agents.mdx, docs/guides/quickstart-relayer.mdx, docs/guides/quickstart-validator.mdx, docs/operate/docker-quickstart.mdx, docs/operate/relayer/run-relayer.mdx, docs/operate/run-docker-compose.mdx, docs/operate/validators/run-validators.mdx
chore: update agent image (v1.4.0)
=> chore: update agent image (v1.4.0)

docs/protocol-economics/intro.mdx
clarification for unstaking flow
=> chore: update protocol economics

docs/reference/alt-vm-implementations/index.mdx
- Add svm mailbox faq
- Update cosmos section: add cosmos sdk
=> feat: update altVM implementation guide 
