docs/operate/relayer/run-relayer.mdx
docs/operate/validators/run-validators.mdx

- It would be better to create a folder if it doesn't exist (that way there is no error if the folder doesn't exist).
- Missing mandatory slashes in commands

Improve ux and fix typos in docker run commands

---

docusaurus.config.js
package.json
yarn.lock

- Adds package for easy redirect configuration
- Drive-by lock packages to latest `3.0.x` patch.
- to avoid issues where plugin would complain of a mismatch with the docusaurus/core package
- will update to `3.1.0` in a separate PR
Note: it'll show as page not found during `yarn start` because the plugin adds redirect to the `yarn build`artifacts. To test locally, run `yarn build && yarn serve`.
Navigate to `https://hyp-v3-docs-git-fix-redirect-imp-guide-abacus-works.vercel.app/docs/protocol/implementation-guide` for an example of the redirect working.

fix: redirect to new implementation-guide

---

docs/protocol/ISM/modular-security.mdx
docs/protocol/ISM/multisig-ISM.mdx
docs/reference/ISM/specify-your-ISM.mdx

- Adds information on module type metadata formats, related to the ISMs for which they are used
- https://github.com/hyperlane-xyz/issues/issues/1194

add ISM module type formats

---

docs/guides/deploy-hyperlane-local-agents.mdx

Fix the `cargo build` command when building `relayer` and `validator` inside `hyperlane-monorepo`

fix: cargo build command

---

src/components/MessageQuickstart.tsx

This PR addresses a syntax error in the example command provided in the MessageQuickstart.tsx file for sending messages using the Hyperlane CLI. 
The original example included an unnecessary quotation mark at the end of the --body parameter, which could lead to execution errors.

Fix Syntax Error in MessageQuickstart.tsx

---

docs/deploy-hyperlane.mdx

As noted by a user, the last step of hyperlane deploy is to deploy a warp route, again. This updates it to the expected instructions of deploying a UI

Update step 6 of hyperlane deploy

---

docs/guides/avs-operator-guide.mdx
docs/guides/create-custom-hook-and-ism.mdx
docs/guides/developer-tips/unit-testing.mdx
docs/guides/ecosystems/solana.mdx
docs/guides/explorer/explorer-debugging.mdx
docs/guides/explorer/graphql-api.mdx
docs/guides/explorer/rest-api.mdx

This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.
Hope it helps.

docs: Rectify typographical inaccuracies

---

docs/reference/hooks/overview.mdx

Add documentation explaining the replayability nature of post-dispatch hooks, and a warning to developers integrating them to be aware of this behavior.
I included it in an INFO box (at the bottom) and it looks like the following image.
The reference implementation I linked is [this](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/b69bc23239ecfc8f8a6277bb0f9bc248cffea234/solidity/contracts/hooks/warp-route/RateLimitedHook.sol#L16).

feat: add post-dispatch hooks replay warning

---

docs/faq.mdx

The link to the documentation in the FAQ was outdated. This PR updates it to point to the correct documentation URL (https://jobs.lever.co/Hyperlane). This ensures users have access to the relevant information.

chore(faq): fix outdated careers page link

---

.gitignore
docs/partials/deploy-hyperlane/_deploy-contracts.mdx

When I went through the guide on (deploying Hyperlane with local agents)[https://docs.hyperlane.xyz/docs/guides/deploy-hyperlane-local-agents], I found that it is not clear what hook to use as default and required ones.
This PR adds a sentence which advises the reader to choose merkle tree hook.
(If there is a better choice of the hook for the purpose of the guide, I can put it into instead of merkle tree hook.)
Additional change:
* Add .idea into .gitignore

Choose merkle tree hook as default and required hook 

---

docs/guides/deploy-warp-route-UI.mdx

Add reference to Warp UI template readme so that developers know how to run Warp UI locally before they deploy it to Vercel or AWS Amplify. The readme contains instructions related WalletConnect Cloud `projectId`.

Add reference to Warp UI template readme

---

docs/partials/warp-routes/commands/_warp-apply-symbol-config-default-strategy.mdx
docs/partials/warp-routes/commands/_warp-apply-symbol-config-default.mdx
src/css/custom.css

- Fix code highlighting to be less jarring. 
- Add linebreak (\) for command

fix: Less jarring code highlighting

---

docs/guides/token-faucets.mdx

filechain Hyperspace Testnet is no longer active. replaced with the current Calibration Testnet.

updating filechain information

---

docs/guides/transfer-warp-route-ownership.mdx

This PR adds a "Warp Route Ownership Overview" section to the Warp Route transfer guide, explaining key responsibilities, security settings, validator options, and relayer support.
Including this info directly in the guide provides important context at the moment users need it, making the transfer process clearer.

feat: add ownership responsibilities and implications clarification

---

docs/operate/relayer/monitoring-alerting.mdx

- Documents `hyperlane_request_count` for monitoring RPC failures in agents

feat: describe `hyperlane_request_count` for monitoring RPC failures in agents

---

docs/guides/message-debugging.mdx
docs/partials/deploy-hyperlane/_deploy-contracts.mdx

This pull request addresses typographical errors in the following files:
1. **`docs/guides/message-debugging.mdx`**:
- Corrected "navigate the the" to "navigate to the".
2. **`docs/partials/deploy-hyperlane/_deploy-contracts.mdx`**:
- Corrected "enviroment" to "environment".

Fix typos in message-debugging.mdx and _deploy-contracts.mdx

---

docs/guides/avs-operator-guide.mdx
docs/guides/create-custom-hook-and-ism.mdx
docs/guides/explorer/rest-api.mdx

**PR includes corrections in configuration and formatting for the Sepolia test network documentation:**
1. Configuration Fixes:
• Updated the nativeToken section in chainConfig, including:
• Added name as “Sepolia ETH”
• Set symbol to “SETH”
• Defined decimals as 18
• Added the URL https://eth-sepolia.public.blastapi.io/ to rpcUrls for increased reliability.
2. Formatting Corrections:
• Added missing colons (:) in configuration lines where necessary.
• Removed extra tab characters at the end of the URL line.
3. Documentation Improvements:
• Fixed typos and minor errors for improved readability.
• Aligned the text with standard practices for better clarity.
**These changes aim to improve configuration accuracy, fix formatting issues, and enhance the readability of the documentation for …

Fix configuration, formatting issues and typos in Sepolia network documentation

---

docs/guides/explorer/configuring-pi-chains.mdx
docs/guides/explorer/explorer-debugging.mdx
docs/guides/explorer/explorer.mdx

While reviewing the docs, found and corrected grammar, spelling errors and typos around [configuring-pi-chains.mdx](https://github.com/hyperlane-xyz/v3-docs/blob/main/docs/guides/explorer/configuring-pi-chains.mdx); [explorer-debugging.mdx](https://github.com/hyperlane-xyz/v3-docs/blob/main/docs/guides/explorer/explorer-debugging.mdx); [explorer.mdx](https://github.com/hyperlane-xyz/v3-docs/blob/main/docs/guides/explorer/explorer.mdx) files

fix: update docs files with errors 

---

docs/operate/config-reference.mdx

fix: log formatting is defined by `log.format`

---

docs/protocol/ISM/third-party-ISMs/optimistic-ISM.mdx
docs/reference/libraries/mailboxclient.mdx
docs/reference/libraries/router.mdx

Fixed broken Router github link on the Router Library page

Fixed broken Router github link on the Router Library page

---

docs/guides/avs-operator-guide.mdx

In the AVS guide under the Confirming Registration section it shows the command to check registration as:
`hyperlane avs check --chain ethereum --operatorAddress <AVS_SIGNING_ADDRESS>`
When it should really be:
`hyperlane avs check --chain ethereum --operatorAddress <EIGENLAYER_OPERATOR_ADDRESS>`

Docs: AVS Guide Correction 

---

package.json
src/components/DefaultValidators.tsx
src/utils/registry.ts
yarn.lock

- update registry
- update `getAbacusWorksChains` to filter out mainnets that are not yet live

feat: update registry

---

docs/guides/quickstart-validator.mdx

Replaced the incorrect usage of "in to" with "into" in the phrase "replace all instances of 'localhost' or '127.0.0.1' into" within the configuration instructions.
Explanation:
- "Into" is used to describe movement or transformation of something into another state or position, which is the correct context here as the instructions guide the user to replace one IP address with another.
- "In to" represents two separate words with distinct meanings and is often used in idiomatic expressions, such as "turn oneself in to the police." However, this does not apply to the current context.
By correcting this usage, the text aligns with proper grammar and improves clarity for users following the setup process.

fix: Correct "in to" to "into" in configuration instructions

---

docs/deploy-hyperlane-troubleshooting.mdx
docs/faq.mdx
docs/protocol/agents/validators.mdx
sidebars.js

- Addressing commonly asked questions on TG 
- Update troubleshooting to include commonly faced errors

docs: update troubleshooting & faq

---

docs/faq.mdx
docs/operate/validators/monitoring-alerting.mdx

Fix typo: "for, instance" -> "for instance"

Fix typo: "for, instance" -> "for instance"

---

docs/guides/deploy-warp-route-UI.mdx
docs/guides/developer-tips/unit-testing.mdx

- Corrected "multi-chain" to "multichain" in `unit-testing.mdx`.
- Added a hyphen to "hassle-free" in `deploy-warp-route-UI.mdx`.

Fix spelling errors

---

docs/partials/deploy-hyperlane/_deploy-contracts.mdx
docs/protocol/warp-routes/warp-routes-yield-routes.mdx

- Fixed capitalization in the following sections:
- "ethereum" to "Ethereum" (in multiple instances)
- "ethereum" to "Ethereum" in variable names and descriptions, ensuring proper noun capitalization.
- Corrected the typo "checkout" to "check out".

Minor text edits and typo corrections

---

docs/protocol/ISM/custom-ISM.mdx

This PR corrects the usage of the `IInterchainSecurityModule` interface in the documentation. The original implementation incorrectly referred to the interface as `IInterchainSecurityModule()` (with parentheses), which is not valid Solidity syntax for an interface name. After verifying the official repository [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/interfaces/IInterchainSecurityModule.sol), it was confirmed that the correct interface name is `IInterchainSecurityModule`.
- Replaced `IInterchainSecurityModule()` with the correct `IInterchainSecurityModule` throughout the documentation.
- Updated related references to ensure accuracy and consistency, such as examples and links to the Hyperlane `verify` and `moduleType` methods.
- Verified …

fix: Correct IInterchainSecurityModule interface usage

---

docs/guides/manage-warp-route-limits.mdx

This pull request fixes a typo in the `manage-warp-route-limits.mdx` file to enhance the clarity and professionalism of the documentation.
- Corrected the word **"funcition"** to **"function"** in the section detailing the `configureController` method.
Accurate documentation ensures better comprehension and usability for developers. Fixing typos helps maintain the quality and professionalism of the project.
---
Feel free to review and suggest any additional changes if needed. Thank you!

fix typo of manage-warp-route-limits.mdx

---

docs/guides/deploy-warp-route.mdx
docs/protocol/warp-routes/warp-routes-example-usage.mdx
docs/protocol/warp-routes/warp-routes-types.mdx

- Update warp route examples section with transaction types
- Enhance the collateral backed and synthetic warp route descriptions on Example usage & warp route types
- Add warp route reference links to the bridge a token guide

chore: improve clarity of Warp Routes types and examples

---

docs/guides/xerc20-warp-route-guide.mdx
sidebars.js

This PR adds a new guide for deploying an xERC20 Warp Route.
**Key changes:**
- Step-by-step guide for setting up xERC20 Warp Routes.
- Covers initialization, deployment, minting permissions, and cross-chain transfers.

feat: add xERC20 Warp Route guide

---

docs/operate/config-reference.mdx
docs/operate/relayer/run-relayer.mdx
docs/operate/validators/run-validators.mdx

This PR addresses issue #301 
- Validator config doc: add multiple rpc url setup 
- Relayer config doc: add multiple rpc url setup 
- Config reference add: customGrpcUrls
- Config reference: prettier formatting

chore: update agent setup docs to clarify mulitple RPC settings

---

README.md
docs/deploy-hyperlane.mdx
docs/guides/create-custom-hook-and-ism.mdx
docs/operate/deploy-with-terraform.mdx
docs/operate/overview-agents.mdx
docs/operate/validators/run-validators.mdx
docs/protocol/agents/validators.mdx
docs/protocol/interchain-gas-payment.mdx
docs/reference/applications/interchain-account.mdx
docs/reference/cli.mdx
docs/reference/hooks/overview.mdx
docs/reference/messaging/send.mdx
docs/reference/registries.mdx
src/diagrams/accounts-implementation.md
src/diagrams/multisig-pos-ism.md
src/diagrams/queries-implementation.md

Mermaid uses `<br>` instead of `\n` for line return
**before:**
**after:**

fix: improve agents overview page and mermaid diagrams line return

---

docs/reference/messaging/receive.mdx

This section of the docs refers to `defaultIsm` but the code block is for a `defaultHook`. Seems like there is no mechanism to keep the code blocks up to date with the docs so maybe we should eliminate the code blocks and encourage people to check out the latest codebase for the relevant functions. I'm glossing over these Solidity function definitions in the docs anyway.

docs: remove irrelevant code block

---

docs/guides/deploy-evm-svm-warp-route.mdx
docs/guides/deploy-svm-warp-route.mdx

- remove the PR that is no longer used
- add instructions to use the hyperlane cli 
- add script to build the programs instead of building them manually

feat: warp route guide improvements 

---

docs/deploy-hyperlane.mdx
docs/guides/deploy-warp-route.mdx
docs/intro.mdx
docs/protocol/warp-routes/warp-routes-overview.mdx
docusaurus.config.js
sidebars.js

- Reorganize sidebar: rename "Getstarted" as Home, move deployments to Home, add VM categorization to Guides/Warp routes
- Update intro 
- Add specific to EVM-based chains warning to guides (bridge a token and deploy to your chain)

feat: docs reorg

---

docs/protocol/agents/relayer.mdx

Adds relayer retry strategy based on https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5712#pullrequestreview-2710136937

feat: add relayer retry strategy

---

docusaurus.config.js
package.json
yarn.lock

Add [plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-vercel-analytics) for vercel analytics.
Note that in development mode the plugin is disabled, so it will only be active in production builds

feat: add docusaurus vercel analytics plugin

---

docs/protocol/ISM/custom-ISM.mdx
docs/protocol/ISM/modular-security.mdx
docs/protocol/ISM/sequence-diagram.mdx
docs/protocol/ISM/third-party-ISMs/OPStack-ISM.mdx
docs/protocol/ISM/third-party-ISMs/arbitrum-L2-to-L1-ISM.mdx
docs/protocol/ISM/third-party-ISMs/community-ISMs.mdx
docs/protocol/ISM/third-party-ISMs/polygon-POS-ISM.mdx
docs/protocol/ISM/third-party-ISMs/wormhole-ISM.mdx
docusaurus.config.js
sidebars.js

feat: update ism section and fixes 
